#!/usr/bin/env python3
"""Generate src/avx/ntt7681_asm_gen.inc for q=7681 n=256 SIMD stages."""

N = 256


def chunks(length):
    if length >= 16:
        for off in range(0, length, 16):
            yield off
    else:
        yield 0


def lazy_lines(start, length, k):
    lines = []
    for off in chunks(length):
        s = start + off
        if length >= 16:
            lines.append(f"  BF_LAZY_YMM {s}, {length}, {k}")
        elif length == 8:
            lines.append(f"  BF_LAZY_XMM8 {start}, {length}, {k}")
        elif length == 4:
            lines.append(f"  BF_LAZY_XMM4 {start}, {length}, {k}")
    return lines


def full_lines(start, length, k):
    lines = []
    for off in chunks(length):
        s = start + off
        if length >= 16:
            lines.append(f"  BF_FULL_YMM {s}, {length}, {k}")
        elif length == 8:
            lines.append(f"  BF_FULL_XMM8 {start}, {length}, {k}")
        elif length == 4:
            lines.append(f"  BF_FULL_XMM4 {start}, {length}, {k}")
    return lines


def inv_lazy_lines(start, length, k):
    lines = []
    for off in chunks(length):
        s = start + off
        if length >= 16:
            lines.append(f"  BF_INV_LAZY_YMM {s}, {length}, {k}")
        elif length == 8:
            lines.append(f"  BF_INV_LAZY_XMM8 {start}, {length}, {k}")
        elif length == 4:
            lines.append(f"  BF_INV_LAZY_XMM4 {start}, {length}, {k}")
    return lines


def inv_full_lines(start, length, k):
    lines = []
    for off in chunks(length):
        s = start + off
        if length >= 16:
            lines.append(f"  BF_INV_FULL_YMM {s}, {length}, {k}")
        elif length == 8:
            lines.append(f"  BF_INV_FULL_XMM8 {start}, {length}, {k}")
        elif length == 4:
            lines.append(f"  BF_INV_FULL_XMM4 {start}, {length}, {k}")
    return lines


def forward_simd():
    lines = []
    k = 1
    for i in [8, 6, 4, 2]:
        ll = 1 << (i - 1)
        if ll == 2:
            break
        for start in range(0, N, 2 * ll):
            lines.extend(lazy_lines(start, ll, k))
            k += 1
        lf = ll >> 1
        for start in range(0, N, 2 * lf):
            lines.extend(full_lines(start, lf, k))
            k += 1
    assert k == 64, k
    return lines


def inverse_simd():
    lines = []
    k = 63
    for i in [2, 4, 6]:
        ll = 1 << i
        for start in range(0, N, 2 * ll):
            lines.extend(inv_lazy_lines(start, ll, k))
            k -= 1
        lf = ll << 1
        for start in range(0, N, 2 * lf):
            lines.extend(inv_full_lines(start, lf, k))
            k -= 1
    assert k == 0, k
    return lines


def main():
    out_path = "src/avx/ntt7681_asm_gen.inc"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("/* auto-generated by tools/gen_ntt7681_asm.py */\n")
        f.write(".macro NTT7681_ASM_FORWARD_SIMD\n")
        for line in forward_simd():
            f.write(line + "\n")
        f.write(".endm\n\n")
        f.write(".macro NTT7681_ASM_INVERSE_SIMD\n")
        for line in inverse_simd():
            f.write(line + "\n")
        f.write(".endm\n")


if __name__ == "__main__":
    main()
